name = "mist"
version = "0.13.2"

licences = ["Apache-2.0"]
description = "a misty Gleam web server"
repository = { type = "github", user = "rawhat", repo = "mist" }
target = "erlang"
gleam = ">= 0.30.0"

[dependencies]
gleam_stdlib = "~> 0.30"
gleam_erlang = "~> 0.19"
gleam_http = "~> 3.3"
glisten = "~> 0.8"
gleam_otp = "~> 0.7"

[dev-dependencies]
gleeunit = "~> 0.10"
gleam_hackney = "~> 1.0"
