name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    name: Gleam test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.1
        with:
          submodules: recursive
      - uses: erlef/setup-beam@v1.15.4
        with:
          otp-version: "25.2"
          gleam-version: "0.32.4"
          rebar3-version: "3"
          elixir-version: "1.14.2"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
